import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import { expect, within } from "storybook/test";
import {
  MdAdd2LineIcon,
  MdAlertLineIcon,
  MdAlertSolid1Icon,
  MdAlertSolidIcon,
  MdAllInclusiveLineIcon,
  MdAppsLineIcon,
  MdArrowBackIosNewLine1Icon,
  MdArrowBackIosNewLineIcon,
  MdArrowBackLineIcon,
  MdArrowDownwardLineIcon,
  MdArrowForwardIosLine1Icon,
  MdArrowForwardIosLineIcon,
  MdArrowForwardLineIcon,
  MdArrowInsertLineIcon,
  MdArrowOutwardLineIcon,
  MdArrowUpwardLineIcon,
  MdAsteriskLineIcon,
  MdBlockLineIcon,
  MdBookmarkLineIcon,
  MdBookmarkSolidIcon,
  MdBugLineIcon,
  MdCalendarSolidIcon,
  MdChartLineIcon,
  MdChatLineIcon,
  MdChatSolidIcon,
  MdCheckLineIcon,
  MdCheckSolidIcon,
  MdCicleSolidIcon,
  MdClipsLineIcon,
  MdClockLineIcon,
  MdCloseLineIcon,
  MdCloseSolidIcon,
  MdCloudLineIcon,
  MdCloudSolidIcon,
  MdCognitionLineIcon,
  MdCookieSolidIcon,
  MdCrownSolidIcon,
  MdDehazeLine1Icon,
  MdDehazeLineIcon,
  MdDeleteLineIcon,
  MdDeleteSolidIcon,
  MdDockToRightLineIcon,
  MdDocLineIcon,
  MdDocSolidIcon,
  MdDownloadLineIcon,
  MdDownloadSolidIcon,
  MdEditSolidIcon,
  MdEmojiSolidIcon,
  MdFavoriteLineIcon,
  MdFavoriteSolidIcon,
  MdFilterLineIcon,
  MdFolderLineIcon,
  MdFolderSolidIcon,
  MdGraphicEqLineIcon,
  MdHelpLineIcon,
  MdHistoryLineIcon,
  MdHomeSolidIcon,
  MdImageLineIcon,
  MdInfoLineIcon,
  MdInfoSolidIcon,
  MdInvoiceLineIcon,
  MdInvoiceSolidIcon,
  MdLanguageLineIcon,
  MdLibrarySolidIcon,
  MdLink2LineIcon,
  MdLockLineIcon,
  MdLockOpenLineIcon,
  MdLockOpenSolidIcon,
  MdLockSolidIcon,
  MdLogoutLineIcon,
  MdMailLineIcon,
  MdMailSolidIcon,
  MdMediumSoundLineIcon,
  MdMediumSoundSolidIcon,
  MdMicLineIcon,
  MdMinusLineIcon,
  MdMoreLineIcon,
  MdMoreSolidIcon,
  MdNoSoundLineIcon,
  MdNoSoundSolidIcon,
  MdNotificationLineIcon,
  MdNotificationOnLineIcon,
  MdNotificationOnSolidIcon,
  MdNotificationSolidIcon,
  MdOpenFolderLineIcon,
  MdOpenFolderSolidIcon,
  MdPhotoCameraLineIcon,
  MdPhotoCameraSolidIcon,
  MdPlaySolidIcon,
  MdPlusSolidIcon,
  MdProfileLineIcon,
  MdQuestionLineIcon,
  MdQuestionSolidIcon,
  MdReturnSolidIcon,
  MdSearchLineIcon,
  MdSettingsLineIcon,
  MdShopLineIcon,
  MdShopSolidIcon,
  MdSoundLineIcon,
  MdSoundSolidIcon,
  MdToolSolidIcon,
  MdUploadLineIcon,
  MdVerifiedLineIcon,
  MdVerifiedShieldLineIcon,
  MdVerifiedShieldSolidIcon,
  MdVerifiedSolidIcon,
  MdVisibilityOnSolidIcon,
  MdVisibilitySolidIcon,
} from "@/components/icons";

const allIcons = [
  { name: "MdAdd2LineIcon", Icon: MdAdd2LineIcon },
  { name: "MdAlertLineIcon", Icon: MdAlertLineIcon },
  { name: "MdAlertSolid1Icon", Icon: MdAlertSolid1Icon },
  { name: "MdAlertSolidIcon", Icon: MdAlertSolidIcon },
  { name: "MdAllInclusiveLineIcon", Icon: MdAllInclusiveLineIcon },
  { name: "MdAppsLineIcon", Icon: MdAppsLineIcon },
  { name: "MdArrowBackIosNewLine1Icon", Icon: MdArrowBackIosNewLine1Icon },
  { name: "MdArrowBackIosNewLineIcon", Icon: MdArrowBackIosNewLineIcon },
  { name: "MdArrowBackLineIcon", Icon: MdArrowBackLineIcon },
  { name: "MdArrowDownwardLineIcon", Icon: MdArrowDownwardLineIcon },
  { name: "MdArrowForwardIosLine1Icon", Icon: MdArrowForwardIosLine1Icon },
  { name: "MdArrowForwardIosLineIcon", Icon: MdArrowForwardIosLineIcon },
  { name: "MdArrowForwardLineIcon", Icon: MdArrowForwardLineIcon },
  { name: "MdArrowInsertLineIcon", Icon: MdArrowInsertLineIcon },
  { name: "MdArrowOutwardLineIcon", Icon: MdArrowOutwardLineIcon },
  { name: "MdArrowUpwardLineIcon", Icon: MdArrowUpwardLineIcon },
  { name: "MdAsteriskLineIcon", Icon: MdAsteriskLineIcon },
  { name: "MdBlockLineIcon", Icon: MdBlockLineIcon },
  { name: "MdBookmarkLineIcon", Icon: MdBookmarkLineIcon },
  { name: "MdBookmarkSolidIcon", Icon: MdBookmarkSolidIcon },
  { name: "MdBugLineIcon", Icon: MdBugLineIcon },
  { name: "MdCalendarSolidIcon", Icon: MdCalendarSolidIcon },
  { name: "MdChartLineIcon", Icon: MdChartLineIcon },
  { name: "MdChatLineIcon", Icon: MdChatLineIcon },
  { name: "MdChatSolidIcon", Icon: MdChatSolidIcon },
  { name: "MdCheckLineIcon", Icon: MdCheckLineIcon },
  { name: "MdCheckSolidIcon", Icon: MdCheckSolidIcon },
  { name: "MdCicleSolidIcon", Icon: MdCicleSolidIcon },
  { name: "MdClipsLineIcon", Icon: MdClipsLineIcon },
  { name: "MdClockLineIcon", Icon: MdClockLineIcon },
  { name: "MdCloseLineIcon", Icon: MdCloseLineIcon },
  { name: "MdCloseSolidIcon", Icon: MdCloseSolidIcon },
  { name: "MdCloudLineIcon", Icon: MdCloudLineIcon },
  { name: "MdCloudSolidIcon", Icon: MdCloudSolidIcon },
  { name: "MdCognitionLineIcon", Icon: MdCognitionLineIcon },
  { name: "MdCookieSolidIcon", Icon: MdCookieSolidIcon },
  { name: "MdCrownSolidIcon", Icon: MdCrownSolidIcon },
  { name: "MdDehazeLine1Icon", Icon: MdDehazeLine1Icon },
  { name: "MdDehazeLineIcon", Icon: MdDehazeLineIcon },
  { name: "MdDeleteLineIcon", Icon: MdDeleteLineIcon },
  { name: "MdDeleteSolidIcon", Icon: MdDeleteSolidIcon },
  { name: "MdDockToRightLineIcon", Icon: MdDockToRightLineIcon },
  { name: "MdDocLineIcon", Icon: MdDocLineIcon },
  { name: "MdDocSolidIcon", Icon: MdDocSolidIcon },
  { name: "MdDownloadLineIcon", Icon: MdDownloadLineIcon },
  { name: "MdDownloadSolidIcon", Icon: MdDownloadSolidIcon },
  { name: "MdEditSolidIcon", Icon: MdEditSolidIcon },
  { name: "MdEmojiSolidIcon", Icon: MdEmojiSolidIcon },
  { name: "MdFavoriteLineIcon", Icon: MdFavoriteLineIcon },
  { name: "MdFavoriteSolidIcon", Icon: MdFavoriteSolidIcon },
  { name: "MdFilterLineIcon", Icon: MdFilterLineIcon },
  { name: "MdFolderLineIcon", Icon: MdFolderLineIcon },
  { name: "MdFolderSolidIcon", Icon: MdFolderSolidIcon },
  { name: "MdGraphicEqLineIcon", Icon: MdGraphicEqLineIcon },
  { name: "MdHelpLineIcon", Icon: MdHelpLineIcon },
  { name: "MdHistoryLineIcon", Icon: MdHistoryLineIcon },
  { name: "MdHomeSolidIcon", Icon: MdHomeSolidIcon },
  { name: "MdImageLineIcon", Icon: MdImageLineIcon },
  { name: "MdInfoLineIcon", Icon: MdInfoLineIcon },
  { name: "MdInfoSolidIcon", Icon: MdInfoSolidIcon },
  { name: "MdInvoiceLineIcon", Icon: MdInvoiceLineIcon },
  { name: "MdInvoiceSolidIcon", Icon: MdInvoiceSolidIcon },
  { name: "MdLanguageLineIcon", Icon: MdLanguageLineIcon },
  { name: "MdLibrarySolidIcon", Icon: MdLibrarySolidIcon },
  { name: "MdLink2LineIcon", Icon: MdLink2LineIcon },
  { name: "MdLockLineIcon", Icon: MdLockLineIcon },
  { name: "MdLockOpenLineIcon", Icon: MdLockOpenLineIcon },
  { name: "MdLockOpenSolidIcon", Icon: MdLockOpenSolidIcon },
  { name: "MdLockSolidIcon", Icon: MdLockSolidIcon },
  { name: "MdLogoutLineIcon", Icon: MdLogoutLineIcon },
  { name: "MdMailLineIcon", Icon: MdMailLineIcon },
  { name: "MdMailSolidIcon", Icon: MdMailSolidIcon },
  { name: "MdMediumSoundLineIcon", Icon: MdMediumSoundLineIcon },
  { name: "MdMediumSoundSolidIcon", Icon: MdMediumSoundSolidIcon },
  { name: "MdMicLineIcon", Icon: MdMicLineIcon },
  { name: "MdMinusLineIcon", Icon: MdMinusLineIcon },
  { name: "MdMoreLineIcon", Icon: MdMoreLineIcon },
  { name: "MdMoreSolidIcon", Icon: MdMoreSolidIcon },
  { name: "MdNoSoundLineIcon", Icon: MdNoSoundLineIcon },
  { name: "MdNoSoundSolidIcon", Icon: MdNoSoundSolidIcon },
  { name: "MdNotificationLineIcon", Icon: MdNotificationLineIcon },
  { name: "MdNotificationOnLineIcon", Icon: MdNotificationOnLineIcon },
  { name: "MdNotificationOnSolidIcon", Icon: MdNotificationOnSolidIcon },
  { name: "MdNotificationSolidIcon", Icon: MdNotificationSolidIcon },
  { name: "MdOpenFolderLineIcon", Icon: MdOpenFolderLineIcon },
  { name: "MdOpenFolderSolidIcon", Icon: MdOpenFolderSolidIcon },
  { name: "MdPhotoCameraLineIcon", Icon: MdPhotoCameraLineIcon },
  { name: "MdPhotoCameraSolidIcon", Icon: MdPhotoCameraSolidIcon },
  { name: "MdPlaySolidIcon", Icon: MdPlaySolidIcon },
  { name: "MdPlusSolidIcon", Icon: MdPlusSolidIcon },
  { name: "MdProfileLineIcon", Icon: MdProfileLineIcon },
  { name: "MdQuestionLineIcon", Icon: MdQuestionLineIcon },
  { name: "MdQuestionSolidIcon", Icon: MdQuestionSolidIcon },
  { name: "MdReturnSolidIcon", Icon: MdReturnSolidIcon },
  { name: "MdSearchLineIcon", Icon: MdSearchLineIcon },
  { name: "MdSettingsLineIcon", Icon: MdSettingsLineIcon },
  { name: "MdShopLineIcon", Icon: MdShopLineIcon },
  { name: "MdShopSolidIcon", Icon: MdShopSolidIcon },
  { name: "MdSoundLineIcon", Icon: MdSoundLineIcon },
  { name: "MdSoundSolidIcon", Icon: MdSoundSolidIcon },
  { name: "MdToolSolidIcon", Icon: MdToolSolidIcon },
  { name: "MdUploadLineIcon", Icon: MdUploadLineIcon },
  { name: "MdVerifiedLineIcon", Icon: MdVerifiedLineIcon },
  { name: "MdVerifiedShieldLineIcon", Icon: MdVerifiedShieldLineIcon },
  { name: "MdVerifiedShieldSolidIcon", Icon: MdVerifiedShieldSolidIcon },
  { name: "MdVerifiedSolidIcon", Icon: MdVerifiedSolidIcon },
  { name: "MdVisibilityOnSolidIcon", Icon: MdVisibilityOnSolidIcon },
  { name: "MdVisibilitySolidIcon", Icon: MdVisibilitySolidIcon },
];

const meta = {
  title: "Icons/Medium",
  tags: ["autodocs"],
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

export const Gallery: Story = {
  render: () => (
    <div className="grid grid-cols-8 gap-4 p-4">
      {allIcons.map(({ name, Icon }) => (
        <div key={name} className="flex flex-col items-center gap-1">
          <Icon className="size-6" />
          <span className="text-[10px] text-muted-foreground truncate w-full text-center">
            {name}
          </span>
        </div>
      ))}
    </div>
  ),
  play: async ({ canvasElement }) => {
    const icons = canvasElement.querySelectorAll("svg");
    await expect(icons.length).toBe(allIcons.length);
  },
};
