import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import { expect } from "storybook/test";
import {
  SmAdd2LineIcon,
  SmAlertLineIcon,
  SmAlertSolid1Icon,
  SmAlertSolidIcon,
  SmAllInclusiveLineIcon,
  SmAppsLineIcon,
  SmArrowBackIosNewLine1Icon,
  SmArrowBackIosNewLineIcon,
  SmArrowBackLineIcon,
  SmArrowDownIosLineIcon,
  SmArrowDownwardLineIcon,
  SmArrowForwardIosLine1Icon,
  SmArrowForwardIosLineIcon,
  SmArrowForwardLineIcon,
  SmArrowInsertLineIcon,
  SmArrowOutwardLineIcon,
  SmArrowUpwardLineIcon,
  SmAsteriskLineIcon,
  SmBlockLineIcon,
  SmBookmarkLineIcon,
  SmBookmarkSolidIcon,
  SmBugLineIcon,
  SmCalendarSolidIcon,
  SmChartLineIcon,
  SmChatLineIcon,
  SmChatSolidIcon,
  SmCheckLineIcon,
  SmCheckSolidIcon,
  SmCicleSolidIcon,
  SmClipsLineIcon,
  SmClockLineIcon,
  SmCloseLineIcon,
  SmCloseSolidIcon,
  SmCloudLineIcon,
  SmCloudSolidIcon,
  SmCognitionLineIcon,
  SmContrastLineIcon,
  SmCookieSolidIcon,
  SmCrownSolidIcon,
  SmDehazeLine1Icon,
  SmDehazeLineIcon,
  SmDeleteLineIcon,
  SmDeleteSolidIcon,
  SmDockToRightLineIcon,
  SmDocLineIcon,
  SmDocSolidIcon,
  SmDownloadLineIcon,
  SmDownloadSolidIcon,
  SmEditSolidIcon,
  SmEmojiSolidIcon,
  SmFavoriteLineIcon,
  SmFavoriteSolidIcon,
  SmFilterLineIcon,
  SmFolderLineIcon,
  SmFolderSolidIcon,
  SmGraphicEqLineIcon,
  SmHelpLineIcon,
  SmHistoryLineIcon,
  SmHomeSolidIcon,
  SmImageLineIcon,
  SmInfoLineIcon,
  SmInfoSolidIcon,
  SmInvoiceLineIcon,
  SmInvoiceSolidIcon,
  SmLanguageLineIcon,
  SmLibrarySolidIcon,
  SmLink2LineIcon,
  SmLockLineIcon,
  SmLockOpenLineIcon,
  SmLockOpenSolidIcon,
  SmLockSolidIcon,
  SmLogoutLineIcon,
  SmMailSolidIcon,
  SmMediumSoundLineIcon,
  SmMediumSoundSolidIcon,
  SmMessageCircleLineIcon,
  SmMessageCircleSolidIcon,
  SmMicLineIcon,
  SmMinusLineIcon,
  SmMoreLineIcon,
  SmMoreSolidIcon,
  SmNoSoundLineIcon,
  SmNoSoundSolidIcon,
  SmNotificationLineIcon,
  SmNotificationOnLineIcon,
  SmNotificationOnSolidIcon,
  SmNotificationSolidIcon,
  SmOpenFolderLineIcon,
  SmOpenFolderSolidIcon,
  SmPhotoCameraLineIcon,
  SmPhotoCameraSolidIcon,
  SmPlaySolidIcon,
  SmPlusSolidIcon,
  SmProfileLineIcon,
  SmQuestionLineIcon,
  SmQuestionSolidIcon,
  SmReturnSolidIcon,
  SmSearchLineIcon,
  SmSettingsLineIcon,
  SmShopLineIcon,
  SmShopSolidIcon,
  SmSoundLineIcon,
  SmSoundSolidIcon,
  SmToolSolidIcon,
  SmUnionLineIcon,
  SmUploadLineIcon,
  SmVerifiedLineIcon,
  SmVerifiedShieldLineIcon,
  SmVerifiedShieldSolidIcon,
  SmVerifiedSolidIcon,
  SmVisibilityOffSolidIcon,
  SmVisibilitySolidIcon,
} from "@/components/icons";

const allIcons = [
  { name: "SmAdd2LineIcon", Icon: SmAdd2LineIcon },
  { name: "SmAlertLineIcon", Icon: SmAlertLineIcon },
  { name: "SmAlertSolid1Icon", Icon: SmAlertSolid1Icon },
  { name: "SmAlertSolidIcon", Icon: SmAlertSolidIcon },
  { name: "SmAllInclusiveLineIcon", Icon: SmAllInclusiveLineIcon },
  { name: "SmAppsLineIcon", Icon: SmAppsLineIcon },
  { name: "SmArrowBackIosNewLine1Icon", Icon: SmArrowBackIosNewLine1Icon },
  { name: "SmArrowBackIosNewLineIcon", Icon: SmArrowBackIosNewLineIcon },
  { name: "SmArrowBackLineIcon", Icon: SmArrowBackLineIcon },
  { name: "SmArrowDownIosLineIcon", Icon: SmArrowDownIosLineIcon },
  { name: "SmArrowDownwardLineIcon", Icon: SmArrowDownwardLineIcon },
  { name: "SmArrowForwardIosLine1Icon", Icon: SmArrowForwardIosLine1Icon },
  { name: "SmArrowForwardIosLineIcon", Icon: SmArrowForwardIosLineIcon },
  { name: "SmArrowForwardLineIcon", Icon: SmArrowForwardLineIcon },
  { name: "SmArrowInsertLineIcon", Icon: SmArrowInsertLineIcon },
  { name: "SmArrowOutwardLineIcon", Icon: SmArrowOutwardLineIcon },
  { name: "SmArrowUpwardLineIcon", Icon: SmArrowUpwardLineIcon },
  { name: "SmAsteriskLineIcon", Icon: SmAsteriskLineIcon },
  { name: "SmBlockLineIcon", Icon: SmBlockLineIcon },
  { name: "SmBookmarkLineIcon", Icon: SmBookmarkLineIcon },
  { name: "SmBookmarkSolidIcon", Icon: SmBookmarkSolidIcon },
  { name: "SmBugLineIcon", Icon: SmBugLineIcon },
  { name: "SmCalendarSolidIcon", Icon: SmCalendarSolidIcon },
  { name: "SmChartLineIcon", Icon: SmChartLineIcon },
  { name: "SmChatLineIcon", Icon: SmChatLineIcon },
  { name: "SmChatSolidIcon", Icon: SmChatSolidIcon },
  { name: "SmCheckLineIcon", Icon: SmCheckLineIcon },
  { name: "SmCheckSolidIcon", Icon: SmCheckSolidIcon },
  { name: "SmCicleSolidIcon", Icon: SmCicleSolidIcon },
  { name: "SmClipsLineIcon", Icon: SmClipsLineIcon },
  { name: "SmClockLineIcon", Icon: SmClockLineIcon },
  { name: "SmCloseLineIcon", Icon: SmCloseLineIcon },
  { name: "SmCloseSolidIcon", Icon: SmCloseSolidIcon },
  { name: "SmCloudLineIcon", Icon: SmCloudLineIcon },
  { name: "SmCloudSolidIcon", Icon: SmCloudSolidIcon },
  { name: "SmCognitionLineIcon", Icon: SmCognitionLineIcon },
  { name: "SmContrastLineIcon", Icon: SmContrastLineIcon },
  { name: "SmCookieSolidIcon", Icon: SmCookieSolidIcon },
  { name: "SmCrownSolidIcon", Icon: SmCrownSolidIcon },
  { name: "SmDehazeLine1Icon", Icon: SmDehazeLine1Icon },
  { name: "SmDehazeLineIcon", Icon: SmDehazeLineIcon },
  { name: "SmDeleteLineIcon", Icon: SmDeleteLineIcon },
  { name: "SmDeleteSolidIcon", Icon: SmDeleteSolidIcon },
  { name: "SmDockToRightLineIcon", Icon: SmDockToRightLineIcon },
  { name: "SmDocLineIcon", Icon: SmDocLineIcon },
  { name: "SmDocSolidIcon", Icon: SmDocSolidIcon },
  { name: "SmDownloadLineIcon", Icon: SmDownloadLineIcon },
  { name: "SmDownloadSolidIcon", Icon: SmDownloadSolidIcon },
  { name: "SmEditSolidIcon", Icon: SmEditSolidIcon },
  { name: "SmEmojiSolidIcon", Icon: SmEmojiSolidIcon },
  { name: "SmFavoriteLineIcon", Icon: SmFavoriteLineIcon },
  { name: "SmFavoriteSolidIcon", Icon: SmFavoriteSolidIcon },
  { name: "SmFilterLineIcon", Icon: SmFilterLineIcon },
  { name: "SmFolderLineIcon", Icon: SmFolderLineIcon },
  { name: "SmFolderSolidIcon", Icon: SmFolderSolidIcon },
  { name: "SmGraphicEqLineIcon", Icon: SmGraphicEqLineIcon },
  { name: "SmHelpLineIcon", Icon: SmHelpLineIcon },
  { name: "SmHistoryLineIcon", Icon: SmHistoryLineIcon },
  { name: "SmHomeSolidIcon", Icon: SmHomeSolidIcon },
  { name: "SmImageLineIcon", Icon: SmImageLineIcon },
  { name: "SmInfoLineIcon", Icon: SmInfoLineIcon },
  { name: "SmInfoSolidIcon", Icon: SmInfoSolidIcon },
  { name: "SmInvoiceLineIcon", Icon: SmInvoiceLineIcon },
  { name: "SmInvoiceSolidIcon", Icon: SmInvoiceSolidIcon },
  { name: "SmLanguageLineIcon", Icon: SmLanguageLineIcon },
  { name: "SmLibrarySolidIcon", Icon: SmLibrarySolidIcon },
  { name: "SmLink2LineIcon", Icon: SmLink2LineIcon },
  { name: "SmLockLineIcon", Icon: SmLockLineIcon },
  { name: "SmLockOpenLineIcon", Icon: SmLockOpenLineIcon },
  { name: "SmLockOpenSolidIcon", Icon: SmLockOpenSolidIcon },
  { name: "SmLockSolidIcon", Icon: SmLockSolidIcon },
  { name: "SmLogoutLineIcon", Icon: SmLogoutLineIcon },
  { name: "SmMailSolidIcon", Icon: SmMailSolidIcon },
  { name: "SmMediumSoundLineIcon", Icon: SmMediumSoundLineIcon },
  { name: "SmMediumSoundSolidIcon", Icon: SmMediumSoundSolidIcon },
  { name: "SmMessageCircleLineIcon", Icon: SmMessageCircleLineIcon },
  { name: "SmMessageCircleSolidIcon", Icon: SmMessageCircleSolidIcon },
  { name: "SmMicLineIcon", Icon: SmMicLineIcon },
  { name: "SmMinusLineIcon", Icon: SmMinusLineIcon },
  { name: "SmMoreLineIcon", Icon: SmMoreLineIcon },
  { name: "SmMoreSolidIcon", Icon: SmMoreSolidIcon },
  { name: "SmNoSoundLineIcon", Icon: SmNoSoundLineIcon },
  { name: "SmNoSoundSolidIcon", Icon: SmNoSoundSolidIcon },
  { name: "SmNotificationLineIcon", Icon: SmNotificationLineIcon },
  { name: "SmNotificationOnLineIcon", Icon: SmNotificationOnLineIcon },
  { name: "SmNotificationOnSolidIcon", Icon: SmNotificationOnSolidIcon },
  { name: "SmNotificationSolidIcon", Icon: SmNotificationSolidIcon },
  { name: "SmOpenFolderLineIcon", Icon: SmOpenFolderLineIcon },
  { name: "SmOpenFolderSolidIcon", Icon: SmOpenFolderSolidIcon },
  { name: "SmPhotoCameraLineIcon", Icon: SmPhotoCameraLineIcon },
  { name: "SmPhotoCameraSolidIcon", Icon: SmPhotoCameraSolidIcon },
  { name: "SmPlaySolidIcon", Icon: SmPlaySolidIcon },
  { name: "SmPlusSolidIcon", Icon: SmPlusSolidIcon },
  { name: "SmProfileLineIcon", Icon: SmProfileLineIcon },
  { name: "SmQuestionLineIcon", Icon: SmQuestionLineIcon },
  { name: "SmQuestionSolidIcon", Icon: SmQuestionSolidIcon },
  { name: "SmReturnSolidIcon", Icon: SmReturnSolidIcon },
  { name: "SmSearchLineIcon", Icon: SmSearchLineIcon },
  { name: "SmSettingsLineIcon", Icon: SmSettingsLineIcon },
  { name: "SmShopLineIcon", Icon: SmShopLineIcon },
  { name: "SmShopSolidIcon", Icon: SmShopSolidIcon },
  { name: "SmSoundLineIcon", Icon: SmSoundLineIcon },
  { name: "SmSoundSolidIcon", Icon: SmSoundSolidIcon },
  { name: "SmToolSolidIcon", Icon: SmToolSolidIcon },
  { name: "SmUnionLineIcon", Icon: SmUnionLineIcon },
  { name: "SmUploadLineIcon", Icon: SmUploadLineIcon },
  { name: "SmVerifiedLineIcon", Icon: SmVerifiedLineIcon },
  { name: "SmVerifiedShieldLineIcon", Icon: SmVerifiedShieldLineIcon },
  { name: "SmVerifiedShieldSolidIcon", Icon: SmVerifiedShieldSolidIcon },
  { name: "SmVerifiedSolidIcon", Icon: SmVerifiedSolidIcon },
  { name: "SmVisibilityOffSolidIcon", Icon: SmVisibilityOffSolidIcon },
  { name: "SmVisibilitySolidIcon", Icon: SmVisibilitySolidIcon },
];

const meta = {
  title: "Icons/Small",
  tags: ["autodocs"],
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

export const Gallery: Story = {
  render: () => (
    <div className="grid grid-cols-8 gap-4 p-4">
      {allIcons.map(({ name, Icon }) => (
        <div key={name} className="flex flex-col items-center gap-1">
          <Icon className="size-5" />
          <span className="text-[10px] text-muted-foreground truncate w-full text-center">
            {name}
          </span>
        </div>
      ))}
    </div>
  ),
  play: async ({ canvasElement }) => {
    const icons = canvasElement.querySelectorAll("svg");
    await expect(icons.length).toBe(allIcons.length);
  },
};
