import type { AssetUploadConfig } from "@/lib/asset-upload-types"

export const audioTypeAssetConfigs: AssetUploadConfig[] = [
  {
    slug: "sons-e-audios",
    title: "Upload de Áudio",
    description:
      "Adicione músicas, efeitos sonoros ou elementos de identidade sonora",
    accept: ".mp3,.wav,.flac,.ogg,.aac,.m4a",
    maxSizeMB: 500,
    multiple: true,
    fields: [
      {
        name: "titulo",
        label: "Título do áudio",
        type: "text",
        required: true,
        placeholder: "Título do áudio",
      },
      {
        name: "tipo",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "musica", label: "Música" },
          { value: "efeito-sonoro", label: "Efeito sonoro" },
          { value: "ambiente-atmosfera", label: "Ambiente/Atmosfera" },
          { value: "vinheta", label: "Vinheta" },
          { value: "narracao", label: "Narração" },
          { value: "sound-logo", label: "Sound logo" },
        ],
      },
      {
        name: "bpm",
        label: "BPM (batidas por minuto)",
        type: "number",
        required: false,
        placeholder: "BPM (batidas por minuto)",
      },
      {
        name: "duracao_segundos",
        label: "Duração em segundos",
        type: "number",
        required: false,
        placeholder: "Duração em segundos",
      },
      {
        name: "mood",
        label: "Mood",
        type: "select",
        required: false,
        options: [
          { value: "energetico", label: "Energético" },
          { value: "calmo", label: "Calmo" },
          { value: "inspirador", label: "Inspirador" },
          { value: "tenso", label: "Tenso" },
          { value: "neutro", label: "Neutro" },
          { value: "epico", label: "Épico" },
          { value: "minimalista", label: "Minimalista" },
        ],
      },
      {
        name: "autor",
        label: "Compositor ou produtor",
        type: "text",
        required: false,
        placeholder: "Compositor ou produtor",
      },
      {
        name: "licenca",
        label: "Licença",
        type: "select",
        required: true,
        options: [
          { value: "propria", label: "Própria" },
          { value: "creative-commons", label: "Creative Commons" },
          { value: "licenciada", label: "Licenciada" },
          { value: "royalty-free", label: "Royalty-free" },
        ],
      },
      {
        name: "loop",
        label: "Loopável",
        type: "switch",
        required: false,
        helperText: "O áudio é loopável?",
      },
      {
        name: "tags",
        label: "Tags",
        type: "tags",
        required: false,
        placeholder: "Ex: instrumental, piano, ambiente, tech...",
      },
      {
        name: "notas",
        label: "Notas",
        type: "textarea",
        required: false,
        placeholder: "Contexto de uso ou restrições",
      },
    ],
  },
  {
    slug: "ativos-de-tipografia",
    title: "Upload de Tipografia",
    description: "Adicione fontes e ativos tipográficos ao acervo",
    accept: ".ttf,.otf,.woff,.woff2,.eot,.zip",
    maxSizeMB: 100,
    multiple: true,
    fields: [
      {
        name: "nome_fonte",
        label: "Nome da família tipográfica",
        type: "text",
        required: true,
        placeholder: "Nome da família tipográfica",
      },
      {
        name: "tipo",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "heading", label: "Heading (títulos)" },
          { value: "body", label: "Body (corpo)" },
          { value: "mono", label: "Mono (monoespaçada)" },
          { value: "display", label: "Display (decorativa)" },
          { value: "handwriting", label: "Handwriting (manuscrita)" },
        ],
      },
      {
        name: "pesos",
        label: "Pesos disponíveis",
        type: "text",
        required: false,
        placeholder: "Pesos disponíveis (ex: 300, 400, 500, 700)",
      },
      {
        name: "formato",
        label: "Formato",
        type: "select",
        required: true,
        options: [
          { value: "ttf", label: "TTF" },
          { value: "otf", label: "OTF" },
          { value: "woff", label: "WOFF" },
          { value: "woff2", label: "WOFF2" },
          { value: "pacote-zip", label: "Pacote (ZIP)" },
        ],
      },
      {
        name: "licenca",
        label: "Licença",
        type: "select",
        required: true,
        options: [
          { value: "open-source", label: "Open Source" },
          { value: "google-fonts", label: "Google Fonts" },
          { value: "adquirida", label: "Adquirida" },
          { value: "proprietaria", label: "Proprietária" },
        ],
      },
      {
        name: "uso_recomendado",
        label: "Uso Recomendado",
        type: "text",
        required: false,
        placeholder: "Ex: títulos H1-H3, corpo de texto, UI...",
      },
      {
        name: "tags",
        label: "Tags",
        type: "tags",
        required: false,
        placeholder: "Ex: sans-serif, geométrica, moderna...",
      },
      {
        name: "notas",
        label: "Notas",
        type: "textarea",
        required: false,
        placeholder: "Observações sobre uso ou integração",
      },
    ],
  },
]
