import type { AssetUploadConfig } from "@/lib/asset-upload-types"

export const contentAssetConfigs: AssetUploadConfig[] = [
  {
    slug: "templates-e-layouts",
    title: "Upload de Template",
    description: "Adicione templates, layouts ou mockups reutilizáveis",
    accept: ".psd,.ai,.fig,.sketch,.pdf,.png,.svg,.xd,.zip",
    maxSizeMB: 500,
    multiple: true,
    fields: [
      {
        name: "titulo",
        label: "Titulo",
        type: "text",
        required: true,
        placeholder: "Nome do template",
      },
      {
        name: "tipo",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "template", label: "Template" },
          { value: "layout", label: "Layout" },
          { value: "mockup", label: "Mockup" },
          { value: "wireframe", label: "Wireframe" },
          { value: "apresentacao", label: "Apresentação" },
        ],
      },
      {
        name: "ferramenta",
        label: "Ferramenta",
        type: "select",
        required: true,
        options: [
          { value: "figma", label: "Figma" },
          { value: "adobe-illustrator", label: "Adobe Illustrator" },
          { value: "adobe-photoshop", label: "Adobe Photoshop" },
          { value: "sketch", label: "Sketch" },
          { value: "adobe-xd", label: "Adobe XD" },
          { value: "canva", label: "Canva" },
          { value: "outro", label: "Outro" },
        ],
      },
      {
        name: "dimensoes",
        label: "Dimensoes",
        type: "text",
        required: false,
        placeholder: "Dimensões (ex: 1920x1080, A4, Stories)",
      },
      {
        name: "categoria_uso",
        label: "Categoria de Uso",
        type: "select",
        required: false,
        options: [
          { value: "social-media", label: "Social media" },
          { value: "apresentacao", label: "Apresentação" },
          { value: "impressao", label: "Impressão" },
          { value: "web-app", label: "Web/App" },
          { value: "e-mail", label: "E-mail" },
          { value: "editorial", label: "Editorial" },
        ],
      },
      {
        name: "editavel",
        label: "Editavel",
        type: "switch",
        required: false,
        helperText: "O template é editável/aberto?",
      },
      {
        name: "tags",
        label: "Tags",
        type: "tags",
        required: false,
        placeholder: "Ex: instagram, apresentação, slide, editorial...",
      },
      {
        name: "notas",
        label: "Notas",
        type: "textarea",
        required: false,
        placeholder: "Instruções de uso ou personalização",
      },
    ],
  },
  {
    slug: "documentacao",
    title: "Upload de Documento",
    description: "Adicione guias, manuais ou documentos de referência",
    accept: ".pdf,.docx,.md,.txt,.pptx,.xlsx,.zip",
    maxSizeMB: 200,
    multiple: true,
    fields: [
      {
        name: "titulo",
        label: "Titulo",
        type: "text",
        required: true,
        placeholder: "Título do documento",
      },
      {
        name: "tipo",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "guia", label: "Guia" },
          { value: "manual", label: "Manual" },
          { value: "referencia", label: "Referência" },
          { value: "apresentacao", label: "Apresentação" },
          { value: "planilha", label: "Planilha" },
          { value: "relatorio", label: "Relatório" },
        ],
      },
      {
        name: "versao",
        label: "Versao",
        type: "text",
        required: false,
        placeholder: "Versão do documento (ex: 1.0, 2.3)",
      },
      {
        name: "publico_alvo",
        label: "Publico Alvo",
        type: "select",
        required: false,
        options: [
          { value: "interno", label: "Interno (equipe)" },
          { value: "parceiros", label: "Parceiros" },
          { value: "clientes", label: "Clientes" },
          { value: "publico-geral", label: "Público geral" },
        ],
      },
      {
        name: "confidencial",
        label: "Confidencial",
        type: "switch",
        required: false,
        helperText: "Documento confidencial/restrito?",
      },
      {
        name: "tags",
        label: "Tags",
        type: "tags",
        required: false,
        placeholder: "Ex: onboarding, brand, processo, guia...",
      },
      {
        name: "notas",
        label: "Notas",
        type: "textarea",
        required: false,
        placeholder: "Resumo do conteúdo ou contexto de uso",
      },
    ],
  },
  {
    slug: "objetos-3d",
    title: "Upload de Objeto 3D",
    description: "Adicione modelos, cenas ou objetos tridimensionais",
    accept: ".glb,.gltf,.obj,.fbx,.blend,.stl,.zip",
    maxSizeMB: 1024,
    multiple: true,
    fields: [
      {
        name: "titulo",
        label: "Titulo",
        type: "text",
        required: true,
        placeholder: "Nome do objeto 3D",
      },
      {
        name: "formato",
        label: "Formato",
        type: "select",
        required: true,
        options: [
          { value: "glb", label: "GLB" },
          { value: "gltf", label: "GLTF" },
          { value: "obj", label: "OBJ" },
          { value: "fbx", label: "FBX" },
          { value: "blender", label: "Blender" },
          { value: "stl", label: "STL" },
          { value: "pacote-zip", label: "Pacote (ZIP)" },
        ],
      },
      {
        name: "polycount",
        label: "Polycount",
        type: "text",
        required: false,
        placeholder: "Polycount aproximado (ex: 50k, 200k)",
      },
      {
        name: "texturizado",
        label: "Texturizado",
        type: "switch",
        required: false,
        helperText: "Possui texturas incluídas?",
      },
      {
        name: "animado",
        label: "Animado",
        type: "switch",
        required: false,
        helperText: "Possui animações?",
      },
      {
        name: "motor_recomendado",
        label: "Motor Recomendado",
        type: "select",
        required: false,
        options: [
          { value: "threejs", label: "Three.js" },
          { value: "blender", label: "Blender" },
          { value: "unity", label: "Unity" },
          { value: "unreal", label: "Unreal" },
          { value: "uso-geral", label: "Uso geral" },
        ],
      },
      {
        name: "tags",
        label: "Tags",
        type: "tags",
        required: false,
        placeholder: "Ex: produto, mockup, cenário, personagem...",
      },
      {
        name: "notas",
        label: "Notas",
        type: "textarea",
        required: false,
        placeholder: "Requisitos técnicos ou instruções de uso",
      },
    ],
  },
]
