import type { AssetUploadConfig } from "@/lib/asset-upload-types"

export const identityAssetConfigs: AssetUploadConfig[] = [
  {
    slug: "simbolos-e-logotipos",
    title: "Upload de Logotipo",
    description: "Adicione novos simbolos ou logotipos ao acervo da marca",
    accept: ".svg,.png,.ai,.eps,.pdf",
    maxSizeMB: 50,
    multiple: true,
    fields: [
      {
        name: "titulo",
        label: "Titulo",
        type: "text",
        required: true,
        placeholder: "Nome do logotipo",
      },
      {
        name: "variante",
        label: "Variante",
        type: "select",
        required: true,
        options: [
          { value: "principal", label: "Principal" },
          { value: "horizontal", label: "Horizontal" },
          { value: "vertical", label: "Vertical" },
          { value: "simbolo", label: "Simbolo" },
          { value: "monograma", label: "Monograma" },
        ],
      },
      {
        name: "formato_uso",
        label: "Formato de Uso",
        type: "select",
        required: true,
        options: [
          { value: "positivo", label: "Positivo" },
          { value: "negativo", label: "Negativo" },
          { value: "colorido", label: "Colorido" },
          { value: "monocromatico", label: "Monocromatico" },
        ],
      },
      {
        name: "fundo",
        label: "Fundo",
        type: "select",
        required: false,
        options: [
          { value: "transparente", label: "Transparente" },
          { value: "claro", label: "Claro" },
          { value: "escuro", label: "Escuro" },
        ],
      },
      {
        name: "tags",
        label: "Tags",
        type: "tags",
        required: false,
        placeholder: "Ex: principal, horizontal, positivo...",
      },
      {
        name: "notas",
        label: "Notas",
        type: "textarea",
        required: false,
        placeholder: "Observacoes sobre uso ou contexto",
      },
    ],
  },
  {
    slug: "biblioteca-de-icones",
    title: "Upload de Icone",
    description: "Adicione novos icones a biblioteca",
    accept: ".svg",
    maxSizeMB: 5,
    multiple: true,
    fields: [
      {
        name: "nome",
        label: "Nome",
        type: "text",
        required: true,
        placeholder: "Nome do icone",
      },
      {
        name: "categoria",
        label: "Categoria",
        type: "select",
        required: true,
        options: [
          { value: "interface", label: "Interface" },
          { value: "ilustrativo", label: "Ilustrativo" },
          { value: "social", label: "Social" },
          { value: "sistema", label: "Sistema" },
          { value: "navegacao", label: "Navegacao" },
        ],
      },
      {
        name: "tamanho_grid",
        label: "Tamanho do Grid",
        type: "select",
        required: false,
        options: [
          { value: "16px", label: "16px" },
          { value: "20px", label: "20px" },
          { value: "24px", label: "24px" },
          { value: "32px", label: "32px" },
          { value: "48px", label: "48px" },
        ],
      },
      {
        name: "tags",
        label: "Tags",
        type: "tags",
        required: false,
      },
      {
        name: "notas",
        label: "Notas",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    slug: "grafismos-e-patterns",
    title: "Upload de Grafismo",
    description: "Adicione grafismos, patterns ou texturas ao acervo",
    accept: ".svg,.png,.ai,.eps,.pdf,.jpg,.jpeg",
    maxSizeMB: 100,
    multiple: true,
    fields: [
      {
        name: "titulo",
        label: "Titulo",
        type: "text",
        required: true,
        placeholder: "Nome do grafismo",
      },
      {
        name: "tipo",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "grafismo", label: "Grafismo" },
          { value: "pattern", label: "Pattern" },
          { value: "textura", label: "Textura" },
          { value: "moldura", label: "Moldura" },
          { value: "elemento-decorativo", label: "Elemento decorativo" },
        ],
      },
      {
        name: "uso_recomendado",
        label: "Uso Recomendado",
        type: "text",
        required: false,
        placeholder: "Ex: backgrounds, bordas, separadores...",
      },
      {
        name: "repetivel",
        label: "Repetivel",
        type: "switch",
        required: false,
        helperText: "O pattern e repetivel/tileable?",
      },
      {
        name: "tags",
        label: "Tags",
        type: "tags",
        required: false,
      },
      {
        name: "notas",
        label: "Notas",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    slug: "ativos-de-cor",
    title: "Upload de Ativo de Cor",
    description: "Adicione paletas, swatches ou referencias cromaticas",
    accept: ".ase,.aco,.svg,.png,.pdf,.json",
    maxSizeMB: 10,
    multiple: true,
    fields: [
      {
        name: "nome",
        label: "Nome",
        type: "text",
        required: true,
        placeholder: "Nome da paleta ou cor",
      },
      {
        name: "tipo",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "paleta-completa", label: "Paleta completa" },
          { value: "swatch-individual", label: "Swatch individual" },
          { value: "gradiente", label: "Gradiente" },
          { value: "referencia-cromatica", label: "Referencia cromatica" },
        ],
      },
      {
        name: "familia",
        label: "Familia",
        type: "select",
        required: false,
        options: [
          { value: "primarias", label: "Primarias" },
          { value: "secundarias", label: "Secundarias" },
          { value: "acentos", label: "Acentos" },
          { value: "neutras", label: "Neutras" },
          { value: "superficies", label: "Superficies" },
        ],
      },
      {
        name: "codigo_hex",
        label: "Codigo Hex",
        type: "text",
        required: false,
        placeholder: "Codigo hex principal (ex: #77C5D5)",
      },
      {
        name: "tags",
        label: "Tags",
        type: "tags",
        required: false,
      },
      {
        name: "notas",
        label: "Notas",
        type: "textarea",
        required: false,
      },
    ],
  },
]
