import type { AssetUploadConfig } from "@/lib/asset-upload-types"

export const mediaAssetConfigs: AssetUploadConfig[] = [
  {
    slug: "banco-de-imagens",
    title: "Upload de Imagem",
    description: "Adicione novas imagens ao banco de imagens da marca",
    accept: ".jpg,.jpeg,.png,.webp,.avif,.tiff",
    maxSizeMB: 200,
    multiple: true,
    fields: [
      {
        name: "titulo",
        label: "Título da imagem",
        type: "text",
        required: true,
        placeholder: "Título da imagem",
      },
      {
        name: "legenda",
        label: "Legenda",
        type: "text",
        required: false,
        placeholder: "Legenda ou caption descritiva",
      },
      {
        name: "autor",
        label: "Autor",
        type: "text",
        required: true,
        placeholder: "Fotógrafo ou autor",
      },
      {
        name: "ano",
        label: "Ano",
        type: "text",
        required: false,
        placeholder: "Ano de produção (ex: 2025)",
      },
      {
        name: "resolucao",
        label: "Resolução",
        type: "select",
        required: false,
        options: [
          { value: "HD", label: "HD (1920x1080)" },
          { value: "2K", label: "2K (2560x1440)" },
          { value: "4K", label: "4K (3840x2160)" },
          { value: "outro", label: "Outro" },
        ],
      },
      {
        name: "orientacao",
        label: "Orientação",
        type: "select",
        required: false,
        options: [
          { value: "horizontal", label: "Horizontal (paisagem)" },
          { value: "vertical", label: "Vertical (retrato)" },
          { value: "quadrado", label: "Quadrado" },
        ],
      },
      {
        name: "licenca",
        label: "Licença",
        type: "select",
        required: false,
        options: [
          { value: "propria", label: "Própria" },
          { value: "creative-commons", label: "Creative Commons" },
          { value: "licenciada", label: "Licenciada" },
          { value: "editorial", label: "Editorial" },
        ],
      },
      {
        name: "tags",
        label: "Tags",
        type: "tags",
        required: false,
        placeholder: "Ex: pessoa, natureza, tecnologia, estúdio...",
      },
      {
        name: "notas",
        label: "Notas",
        type: "textarea",
        required: false,
        placeholder: "Contexto de produção ou restrições de uso",
      },
    ],
  },
  {
    slug: "banco-de-videos",
    title: "Upload de Vídeo",
    description: "Adicione novos vídeos ou footages ao banco audiovisual",
    accept: ".mp4,.mov,.webm,.avi",
    maxSizeMB: 2048,
    multiple: false,
    fields: [
      {
        name: "titulo",
        label: "Título do vídeo",
        type: "text",
        required: true,
        placeholder: "Título do vídeo",
      },
      {
        name: "resolucao",
        label: "Resolução",
        type: "select",
        required: true,
        options: [
          { value: "HD", label: "HD (1920x1080)" },
          { value: "3K", label: "3K (3072x1728)" },
          { value: "4K", label: "4K (3840x2160)" },
          { value: "4-6K", label: "4-6K (4608x2592)" },
        ],
      },
      {
        name: "orientacao",
        label: "Orientação",
        type: "select",
        required: true,
        options: [
          { value: "horiz", label: "Horizontal (paisagem)" },
          { value: "vert", label: "Vertical (retrato)" },
        ],
      },
      {
        name: "duracao",
        label: "Duração",
        type: "select",
        required: true,
        options: [
          { value: "short", label: "Curta (< 10s)" },
          { value: "medium", label: "Média (10-30s)" },
          { value: "long", label: "Longa (> 30s)" },
        ],
      },
      {
        name: "fps",
        label: "FPS",
        type: "select",
        required: false,
        options: [
          { value: "24", label: "24fps" },
          { value: "25", label: "25fps" },
          { value: "30", label: "30fps" },
          { value: "60", label: "60fps" },
          { value: "120", label: "120fps" },
        ],
      },
      {
        name: "tem_audio",
        label: "Contém áudio",
        type: "switch",
        required: false,
        helperText: "O vídeo contém áudio?",
      },
      {
        name: "autor",
        label: "Autor",
        type: "text",
        required: true,
        placeholder: "Autor ou videógrafo",
      },
      {
        name: "licenca",
        label: "Licença",
        type: "select",
        required: false,
        options: [
          { value: "propria", label: "Própria" },
          { value: "creative-commons", label: "Creative Commons" },
          { value: "licenciada", label: "Licenciada" },
          { value: "editorial", label: "Editorial" },
        ],
      },
      {
        name: "tags",
        label: "Tags",
        type: "tags",
        required: false,
        placeholder: "Ex: natureza, aéreo, câmera-lenta, tecnologia...",
      },
      {
        name: "notas",
        label: "Notas",
        type: "textarea",
        required: false,
        placeholder: "Contexto de produção ou restrições de uso",
      },
    ],
  },
]
